const DATA = {
  suppliers: [
    { id:"sup-001", name:"Redwood Packaging Co.", category:"Packaging", city:"Manchester", owed:18420, lastPayment:"Mar 28", color:"#B04A1D", initial:"R", contactName:"Sarah Mitchell", email:"sarah@redwoodpkg.co.uk", phone:"0161 496 0142", address:"Unit 4, Trafford Park, Manchester M17 1HB", paymentMethod:"Bank Transfer", bankName:"Barclays", accountLast4:"4829", terms:"Net 30", taxId:"GB 943 218 745", paidYTD:72840, invoiceCount:14, tags:["Preferred","Volume Discount"], sortCode:"200100", accountNumber:"55779911" },
    { id:"sup-002", name:"Meridian Logistics", category:"Freight", city:"Birmingham", owed:12850, lastPayment:"Apr 2", color:"#2B5BD7", initial:"M", contactName:"James Thornton", email:"j.thornton@meridianlog.co.uk", phone:"0121 355 0198", address:"24 Colmore Row, Birmingham B3 2QD", paymentMethod:"Bank Transfer", bankName:"NatWest", accountLast4:"7753", terms:"Net 15", taxId:"GB 937 654 102", paidYTD:54200, invoiceCount:9, tags:["Priority"], sortCode:"200200", accountNumber:"55779911" },
    { id:"sup-003", name:"Kettle & Hearth Supplies", category:"Catering", city:"Bristol", owed:8340, lastPayment:"Mar 22", color:"#6B4C9A", initial:"K", contactName:"Emma Caldwell", email:"emma@kettlehearth.co.uk", phone:"0117 496 0267", address:"15 Whiteladies Road, Bristol BS8 1PB", paymentMethod:"Bank Transfer", bankName:"Lloyds", accountLast4:"3312", terms:"Net 30", taxId:"GB 845 091 823", paidYTD:36720, invoiceCount:11, tags:["Catering","Monthly"], sortCode:"300100", accountNumber:"55779911" },
    { id:"sup-004", name:"Juniper Cleaning Services", category:"Facilities", city:"Leeds", owed:3215, lastPayment:"Apr 5", color:"#2F6E3E", initial:"J", contactName:"David Park", email:"david@junipercleaning.co.uk", phone:"0113 496 0334", address:"8 Park Row, Leeds LS1 5HD", paymentMethod:"Bank Transfer", bankName:"HSBC", accountLast4:"9981", terms:"Net 15", taxId:"GB 912 834 567", paidYTD:19290, invoiceCount:6, tags:["Recurring"], sortCode:"040000", accountNumber:"55779911" },
    { id:"sup-005", name:"Blackstone Printing", category:"Print", city:"Edinburgh", owed:6780, lastPayment:"Mar 15", color:"#1A1A1A", initial:"B", contactName:"Liam Foster", email:"liam@blackstoneprint.co.uk", phone:"0131 496 0421", address:"52 George Street, Edinburgh EH2 2LR", paymentMethod:"Bank Transfer", bankName:"Royal Bank of Scotland", accountLast4:"6014", terms:"Net 45", taxId:"GB 368 745 213", paidYTD:28450, invoiceCount:8, tags:["Print","Marketing"], sortCode:"201000", accountNumber:"55779911" },
    { id:"sup-006", name:"Olive & Oak Linen Co.", category:"Linen", city:"Bath", owed:4920, lastPayment:"Apr 1", color:"#8B6914", initial:"O", contactName:"Grace Bennett", email:"grace@oliveoak.co.uk", phone:"01225 496 589", address:"3 Milsom Street, Bath BA1 1DA", paymentMethod:"Bank Transfer", bankName:"Lloyds", accountLast4:"2247", terms:"Net 30", taxId:"GB 623 019 847", paidYTD:21560, invoiceCount:7, tags:["Linen","Hospitality"], sortCode:"300200", accountNumber:"55779911" },
    { id:"sup-007", name:"Farrow Materials", category:"Raw Materials", city:"Sheffield", owed:22150, lastPayment:"Mar 30", color:"#C23030", initial:"F", contactName:"Marcus Webb", email:"marcus@farrowmat.co.uk", phone:"0114 496 0673", address:"140 West Street, Sheffield S1 4ES", paymentMethod:"Bank Transfer", bankName:"Barclays", accountLast4:"5538", terms:"Net 30", taxId:"GB 746 120 398", paidYTD:98700, invoiceCount:18, tags:["Bulk","Critical"], sortCode:"200300", accountNumber:"55779911" },
    { id:"sup-008", name:"Northgate Facilities", category:"Maintenance", city:"Glasgow", owed:2450, lastPayment:"Apr 8", color:"#3A4558", initial:"N", contactName:"Olivia Chen", email:"olivia@northgatefac.co.uk", phone:"0141 496 0712", address:"200 Broomielaw, Glasgow G1 4RU", paymentMethod:"Bank Transfer", bankName:"Clydesdale Bank", accountLast4:"8803", terms:"Net 15", taxId:"GB 049 283 746", paidYTD:14700, invoiceCount:5, tags:["Maintenance"], sortCode:"301000", accountNumber:"55779911" },
    { id:"sup-009", name:"Summit Ingredients", category:"Food Supply", city:"London", owed:15670, lastPayment:"Apr 3", color:"#16794E", initial:"S", contactName:"Noah Reeves", email:"noah@summitingredients.co.uk", phone:"020 7496 0856", address:"45 Borough Market, London SE1 9AH", paymentMethod:"Bank Transfer", bankName:"Barclays", accountLast4:"1176", terms:"Net 30", taxId:"GB 941 827 365", paidYTD:68340, invoiceCount:16, tags:["Food","Weekly Orders"], sortCode:"200400", accountNumber:"55779911" },
    { id:"sup-010", name:"Avalon Freight Solutions", category:"Logistics", city:"Cardiff", owed:9580, lastPayment:"Mar 25", color:"#B25A1C", initial:"A", contactName:"Isabella Torres", email:"isabella@avalonfreight.co.uk", phone:"029 2049 0943", address:"18 St Mary Street, Cardiff CF10 1DX", paymentMethod:"Bank Transfer", bankName:"HSBC", accountLast4:"4410", terms:"Net 30", taxId:"GB 597 362 841", paidYTD:42100, invoiceCount:10, tags:["Freight","International"], sortCode:"040100", accountNumber:"55779911" },
  ],

  invoices: [
    { id:"inv-001", number:"INV-4821", supplierId:"sup-001", supplierName:"Redwood Packaging Co.", supplierColor:"#B04A1D", supplierInitial:"R", issued:"Mar 1", due:"Mar 31", amount:8420, status:"overdue", daysUntilDue:-19, category:"Packaging", paidDate:null, paymentMethod:null, discount:null, needsApproval:false,
      lineItems:[{desc:"Custom corrugated boxes (200 units)",qty:200,unit:32.50},{desc:"Bubble wrap rolls (50m)",qty:10,unit:19.20},{desc:"Packing tape (bulk)",qty:24,unit:4.50}],
      subtotal:6800, taxRate:0.20, tax:1360, notes:"Urgent restock order", poNumber:"PO-2026-0412", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Redwood Packaging Co.",status:"done",date:"Mar 1"},{title:"Received",sub:"Accounts payable",status:"done",date:"Mar 3"},{title:"Approved",sub:"Sarah Mitchell",status:"done",date:"Mar 5"},{title:"Payment due",sub:"19 days overdue",status:"warning",date:"Mar 31"}] },
    { id:"inv-002", number:"INV-4822", supplierId:"sup-007", supplierName:"Farrow Materials", supplierColor:"#C23030", supplierInitial:"F", issued:"Mar 5", due:"Apr 4", amount:12150, status:"overdue", daysUntilDue:-15, category:"Raw Materials", paidDate:null, paymentMethod:null, discount:"2% early pay", needsApproval:true,
      lineItems:[{desc:"Steel sheet 4x8 (20 gauge)",qty:50,unit:185.00},{desc:"Aluminium bar stock",qty:30,unit:42.00},{desc:"Delivery surcharge",qty:1,unit:190.00}],
      subtotal:10700, taxRate:0.20, tax:2140, notes:null, poNumber:"PO-2026-0418", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Farrow Materials",status:"done",date:"Mar 5"},{title:"Received",sub:"Accounts payable",status:"done",date:"Mar 7"},{title:"Pending approval",sub:"Needs manager sign-off",status:"warning",date:"Mar 10"},{title:"Payment due",sub:"15 days overdue",status:"warning",date:"Apr 4"}] },
    { id:"inv-003", number:"INV-4823", supplierId:"sup-002", supplierName:"Meridian Logistics", supplierColor:"#2B5BD7", supplierInitial:"M", issued:"Apr 2", due:"Apr 22", amount:5280, status:"due", daysUntilDue:3, category:"Freight", paidDate:null, paymentMethod:null, discount:null, needsApproval:false,
      lineItems:[{desc:"Freight Manchester - London",qty:2,unit:1840.00},{desc:"Fuel surcharge",qty:2,unit:275.00},{desc:"Liftgate service",qty:1,unit:50.00}],
      subtotal:4280, taxRate:0.20, tax:856, notes:"Expedited shipment", poNumber:"PO-2026-0445", terms:"Net 15",
      timeline:[{title:"Invoice issued",sub:"Meridian Logistics",status:"done",date:"Apr 2"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 3"},{title:"Approved",sub:"James Thornton",status:"done",date:"Apr 5"},{title:"Payment due",sub:"Due in 3 days",status:"current",date:"Apr 22"}] },
    { id:"inv-004", number:"INV-4824", supplierId:"sup-003", supplierName:"Kettle & Hearth Supplies", supplierColor:"#6B4C9A", supplierInitial:"K", issued:"Apr 1", due:"May 1", amount:3420, status:"due", daysUntilDue:12, category:"Catering", paidDate:null, paymentMethod:null, discount:null, needsApproval:false,
      lineItems:[{desc:"Commercial coffee beans (10kg)",qty:5,unit:420.00},{desc:"Disposable cups (500 pack)",qty:3,unit:185.00},{desc:"Stir sticks (box of 1000)",qty:2,unit:22.50}],
      subtotal:2700, taxRate:0.20, tax:540, notes:null, poNumber:"PO-2026-0441", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Kettle & Hearth",status:"done",date:"Apr 1"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 2"},{title:"Approved",sub:"Auto-approved",status:"done",date:"Apr 2"},{title:"Payment due",sub:"Due in 12 days",status:"current",date:"May 1"}] },
    { id:"inv-005", number:"INV-4825", supplierId:"sup-009", supplierName:"Summit Ingredients", supplierColor:"#16794E", supplierInitial:"S", issued:"Apr 5", due:"May 5", amount:7890, status:"due", daysUntilDue:16, category:"Food Supply", paidDate:null, paymentMethod:null, discount:"1.5% Net 10", needsApproval:false,
      lineItems:[{desc:"Organic flour (25kg bags)",qty:20,unit:245.00},{desc:"Olive oil (5L tins)",qty:12,unit:89.50},{desc:"Sea salt (bulk 10kg)",qty:8,unit:34.00}],
      subtotal:6446, taxRate:0.20, tax:1289.20, notes:"Weekly standing order", poNumber:"PO-2026-0450", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Summit Ingredients",status:"done",date:"Apr 5"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 6"},{title:"Approved",sub:"Noah Reeves",status:"done",date:"Apr 7"},{title:"Payment due",sub:"Due in 16 days",status:"current",date:"May 5"}] },
    { id:"inv-006", number:"INV-4826", supplierId:"sup-005", supplierName:"Blackstone Printing", supplierColor:"#1A1A1A", supplierInitial:"B", issued:"Apr 3", due:"May 18", amount:2340, status:"due", daysUntilDue:29, category:"Print", paidDate:null, paymentMethod:null, discount:null, needsApproval:true,
      lineItems:[{desc:"Product catalogue (500 copies)",qty:500,unit:3.20},{desc:"Business cards (200 sets)",qty:200,unit:2.10},{desc:"Design revision fee",qty:1,unit:180.00}],
      subtotal:1980, taxRate:0.20, tax:396, notes:"Spring marketing campaign", poNumber:"PO-2026-0447", terms:"Net 45",
      timeline:[{title:"Invoice issued",sub:"Blackstone Printing",status:"done",date:"Apr 3"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 4"},{title:"Pending approval",sub:"Waiting for review",status:"current",date:"Apr 5"},{title:"Payment due",sub:"Due in 29 days",status:"pending",date:"May 18"}] },
    { id:"inv-007", number:"INV-4827", supplierId:"sup-004", supplierName:"Juniper Cleaning Services", supplierColor:"#2F6E3E", supplierInitial:"J", issued:"Apr 8", due:"Apr 23", amount:1580, status:"due", daysUntilDue:4, category:"Facilities", paidDate:null, paymentMethod:null, discount:null, needsApproval:false,
      lineItems:[{desc:"Office deep clean (monthly)",qty:1,unit:980.00},{desc:"Carpet steam clean",qty:1,unit:350.00},{desc:"Cleaning supplies restock",qty:1,unit:132.50}],
      subtotal:1462.50, taxRate:0.20, tax:117.50, notes:null, poNumber:null, terms:"Net 15",
      timeline:[{title:"Invoice issued",sub:"Juniper Cleaning",status:"done",date:"Apr 8"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 9"},{title:"Approved",sub:"Auto-approved",status:"done",date:"Apr 9"},{title:"Payment due",sub:"Due in 4 days",status:"current",date:"Apr 23"}] },
    { id:"inv-008", number:"INV-4828", supplierId:"sup-010", supplierName:"Avalon Freight Solutions", supplierColor:"#B25A1C", supplierInitial:"A", issued:"Apr 6", due:"May 6", amount:4760, status:"due", daysUntilDue:17, category:"Logistics", paidDate:null, paymentMethod:null, discount:null, needsApproval:false,
      lineItems:[{desc:"Container shipment Cardiff - London",qty:1,unit:3200.00},{desc:"Port handling fees",qty:1,unit:480.00},{desc:"Insurance (cargo)",qty:1,unit:228.33}],
      subtotal:3908.33, taxRate:0.20, tax:781.67, notes:"Import shipment Q2", poNumber:"PO-2026-0452", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Avalon Freight",status:"done",date:"Apr 6"},{title:"Received",sub:"Accounts payable",status:"done",date:"Apr 7"},{title:"Approved",sub:"Isabella Torres",status:"done",date:"Apr 9"},{title:"Payment due",sub:"Due in 17 days",status:"current",date:"May 6"}] },
    { id:"inv-009", number:"INV-4829", supplierId:"sup-006", supplierName:"Olive & Oak Linen Co.", supplierColor:"#8B6914", supplierInitial:"O", issued:"Apr 10", due:"May 10", amount:2460, status:"draft", daysUntilDue:21, category:"Linen", paidDate:null, paymentMethod:null, discount:null, needsApproval:true,
      lineItems:[{desc:"Table linens (white, 60x120)",qty:30,unit:48.00},{desc:"Napkins (cotton, pack of 12)",qty:20,unit:24.00},{desc:"Embroidery service",qty:30,unit:8.00}],
      subtotal:2160, taxRate:0.20, tax:432, notes:"New design - awaiting sample approval", poNumber:null, terms:"Net 30",
      timeline:[{title:"Draft created",sub:"Olive & Oak Linen",status:"done",date:"Apr 10"},{title:"Pending review",sub:"Awaiting confirmation",status:"current",date:"Apr 12"},{title:"Approval",sub:"Not started",status:"pending",date:""},{title:"Payment due",sub:"Not scheduled",status:"pending",date:"May 10"}] },
    { id:"inv-010", number:"INV-4830", supplierId:"sup-008", supplierName:"Northgate Facilities", supplierColor:"#3A4558", supplierInitial:"N", issued:"Mar 25", due:"Apr 9", amount:2450, status:"processing", daysUntilDue:null, category:"Maintenance", paidDate:null, paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"HVAC quarterly service",qty:1,unit:1450.00},{desc:"Filter replacements (set of 6)",qty:1,unit:480.00},{desc:"Emergency call-out (Mar 18)",qty:1,unit:111.67}],
      subtotal:2041.67, taxRate:0.20, tax:408.33, notes:null, poNumber:"PO-2026-0435", terms:"Net 15",
      timeline:[{title:"Invoice issued",sub:"Northgate Facilities",status:"done",date:"Mar 25"},{title:"Approved",sub:"Auto-approved",status:"done",date:"Mar 26"},{title:"Payment initiated",sub:"Bank Transfer",status:"current",date:"Apr 9"},{title:"Settlement",sub:"Expected Apr 11",status:"pending",date:"Apr 11"}] },
    { id:"inv-011", number:"INV-4831", supplierId:"sup-001", supplierName:"Redwood Packaging Co.", supplierColor:"#B04A1D", supplierInitial:"R", issued:"Feb 15", due:"Mar 17", amount:5640, status:"paid", daysUntilDue:null, category:"Packaging", paidDate:"Mar 15", paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"Shipping cartons (150 units)",qty:150,unit:28.50},{desc:"Cushion wrap",qty:20,unit:14.75}],
      subtotal:4570, taxRate:0.20, tax:914, notes:null, poNumber:"PO-2026-0398", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Redwood Packaging",status:"done",date:"Feb 15"},{title:"Approved",sub:"Sarah Mitchell",status:"done",date:"Feb 17"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Mar 15"},{title:"Settled",sub:"Confirmed",status:"done",date:"Mar 17"}] },
    { id:"inv-012", number:"INV-4832", supplierId:"sup-002", supplierName:"Meridian Logistics", supplierColor:"#2B5BD7", supplierInitial:"M", issued:"Mar 1", due:"Mar 16", amount:3870, status:"paid", daysUntilDue:null, category:"Freight", paidDate:"Mar 14", paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"Freight Birmingham - Bristol",qty:1,unit:3200.00},{desc:"Fuel surcharge",qty:1,unit:25.00}],
      subtotal:3225, taxRate:0.20, tax:645, notes:null, poNumber:"PO-2026-0410", terms:"Net 15",
      timeline:[{title:"Invoice issued",sub:"Meridian Logistics",status:"done",date:"Mar 1"},{title:"Approved",sub:"James Thornton",status:"done",date:"Mar 3"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Mar 14"},{title:"Settled",sub:"Confirmed",status:"done",date:"Mar 17"}] },
    { id:"inv-013", number:"INV-4833", supplierId:"sup-009", supplierName:"Summit Ingredients", supplierColor:"#16794E", supplierInitial:"S", issued:"Mar 10", due:"Apr 9", amount:6540, status:"paid", daysUntilDue:null, category:"Food Supply", paidDate:"Apr 7", paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"Premium vanilla extract (1L)",qty:8,unit:340.00},{desc:"Cocoa powder (5kg)",qty:15,unit:165.00},{desc:"Baking soda (bulk 20kg)",qty:4,unit:42.50}],
      subtotal:5365, taxRate:0.20, tax:1073, notes:null, poNumber:"PO-2026-0420", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Summit Ingredients",status:"done",date:"Mar 10"},{title:"Approved",sub:"Noah Reeves",status:"done",date:"Mar 12"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Apr 7"},{title:"Settled",sub:"Confirmed",status:"done",date:"Apr 9"}] },
    { id:"inv-014", number:"INV-4834", supplierId:"sup-004", supplierName:"Juniper Cleaning Services", supplierColor:"#2F6E3E", supplierInitial:"J", issued:"Mar 5", due:"Mar 20", amount:1420, status:"paid", daysUntilDue:null, category:"Facilities", paidDate:"Mar 19", paymentMethod:"Faster Payment", discount:null, needsApproval:false,
      lineItems:[{desc:"Monthly office clean",qty:1,unit:980.00},{desc:"Window cleaning (exterior)",qty:1,unit:203.33}],
      subtotal:1183.33, taxRate:0.20, tax:236.67, notes:null, poNumber:null, terms:"Net 15",
      timeline:[{title:"Invoice issued",sub:"Juniper Cleaning",status:"done",date:"Mar 5"},{title:"Approved",sub:"Auto-approved",status:"done",date:"Mar 5"},{title:"Payment sent",sub:"Faster Payment",status:"done",date:"Mar 19"},{title:"Settled",sub:"Confirmed",status:"done",date:"Mar 20"}] },
    { id:"inv-015", number:"INV-4835", supplierId:"sup-007", supplierName:"Farrow Materials", supplierColor:"#C23030", supplierInitial:"F", issued:"Feb 28", due:"Mar 30", amount:9800, status:"paid", daysUntilDue:null, category:"Raw Materials", paidDate:"Mar 28", paymentMethod:"Bank Transfer", discount:"2% early pay", needsApproval:false,
      lineItems:[{desc:"Copper tubing (100m)",qty:100,unit:72.00},{desc:"Brass fittings (assorted)",qty:200,unit:8.50},{desc:"Delivery",qty:1,unit:33.33}],
      subtotal:8133.33, taxRate:0.20, tax:1626.67, notes:null, poNumber:"PO-2026-0405", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Farrow Materials",status:"done",date:"Feb 28"},{title:"Approved",sub:"Marcus Webb",status:"done",date:"Mar 2"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Mar 28"},{title:"Settled",sub:"Confirmed",status:"done",date:"Mar 31"}] },
    { id:"inv-016", number:"INV-4836", supplierId:"sup-003", supplierName:"Kettle & Hearth Supplies", supplierColor:"#6B4C9A", supplierInitial:"K", issued:"Mar 8", due:"Apr 7", amount:2180, status:"paid", daysUntilDue:null, category:"Catering", paidDate:"Apr 5", paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"Tea selection box (12 varieties)",qty:10,unit:135.00},{desc:"Sugar sachets (box of 500)",qty:5,unit:28.00},{desc:"Milk portions (crate of 120)",qty:8,unit:18.75}],
      subtotal:1640, taxRate:0.20, tax:328, notes:null, poNumber:"PO-2026-0415", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Kettle & Hearth",status:"done",date:"Mar 8"},{title:"Approved",sub:"Emma Caldwell",status:"done",date:"Mar 10"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Apr 5"},{title:"Settled",sub:"Confirmed",status:"done",date:"Apr 7"}] },
    { id:"inv-017", number:"INV-4837", supplierId:"sup-010", supplierName:"Avalon Freight Solutions", supplierColor:"#B25A1C", supplierInitial:"A", issued:"Mar 12", due:"Apr 11", amount:4820, status:"paid", daysUntilDue:null, category:"Logistics", paidDate:"Apr 10", paymentMethod:"Bank Transfer", discount:null, needsApproval:false,
      lineItems:[{desc:"Air freight Cardiff - Edinburgh",qty:1,unit:3800.00},{desc:"Customs clearance",qty:1,unit:250.00},{desc:"Handling fees",qty:1,unit:166.67}],
      subtotal:4216.67, taxRate:0.20, tax:843.33, notes:"Time-sensitive shipment", poNumber:"PO-2026-0425", terms:"Net 30",
      timeline:[{title:"Invoice issued",sub:"Avalon Freight",status:"done",date:"Mar 12"},{title:"Approved",sub:"Isabella Torres",status:"done",date:"Mar 14"},{title:"Payment sent",sub:"Bank Transfer",status:"done",date:"Apr 10"},{title:"Settled",sub:"Confirmed",status:"done",date:"Apr 10"}] },
  ],

  approvals: [
    { id:"apr-001", supplierId:"sup-007", supplierName:"Farrow Materials", supplierInitial:"F", supplierColor:"#C23030", invoiceNumber:"INV-4822", amount:12150, due:"Apr 4", dueIn:"15 days overdue", urgent:true, category:"Raw Materials", status:"pending", submittedBy:"Alex Rivera", submittedAt:"Mar 10, 9:14 AM",
      lineItems:[{desc:"Steel sheet 4x8 (20 gauge)",qty:50,unit:185.00},{desc:"Aluminium bar stock",qty:30,unit:42.00},{desc:"Delivery surcharge",qty:1,unit:190.00}],
      subtotal:10700, tax:2140,
      thread:[{time:"Mar 10 9:14 AM",kind:"submitted",who:"Alex Rivera",body:"Urgent restock needed. Steel inventory critically low."},{time:"Mar 12 2:30 PM",kind:"note",who:"Jordan Lee",body:"Checked with warehouse - confirmed we need this by end of month."}],
      needsFollowUp:true, approvedBy:null, approvedAt:null },
    { id:"apr-002", supplierId:"sup-005", supplierName:"Blackstone Printing", supplierInitial:"B", supplierColor:"#1A1A1A", invoiceNumber:"INV-4826", amount:2340, due:"May 18", dueIn:"29 days", urgent:false, category:"Print", status:"pending", submittedBy:"Casey Morgan", submittedAt:"Apr 5, 11:22 AM",
      lineItems:[{desc:"Product catalogue (500 copies)",qty:500,unit:3.20},{desc:"Business cards (200 sets)",qty:200,unit:2.10},{desc:"Design revision fee",qty:1,unit:180.00}],
      subtotal:1980, tax:396,
      thread:[{time:"Apr 5 11:22 AM",kind:"submitted",who:"Casey Morgan",body:"Spring marketing campaign materials. Design approved by marketing team."}],
      needsFollowUp:false, approvedBy:null, approvedAt:null },
    { id:"apr-003", supplierId:"sup-006", supplierName:"Olive & Oak Linen Co.", supplierInitial:"O", supplierColor:"#8B6914", invoiceNumber:"INV-4829", amount:2460, due:"May 10", dueIn:"21 days", urgent:false, category:"Linen", status:"pending", submittedBy:"Taylor Kim", submittedAt:"Apr 12, 3:45 PM",
      lineItems:[{desc:"Table linens (white, 60x120)",qty:30,unit:48.00},{desc:"Napkins (cotton, pack of 12)",qty:20,unit:24.00},{desc:"Embroidery service",qty:30,unit:8.00}],
      subtotal:2160, tax:432,
      thread:[{time:"Apr 12 3:45 PM",kind:"submitted",who:"Taylor Kim",body:"New linen order for summer season. Samples approved last week."},{time:"Apr 14 10:00 AM",kind:"note",who:"Taylor Kim",body:"Grace at Olive & Oak confirmed 2-week lead time if we order by Apr 20."}],
      needsFollowUp:false, approvedBy:null, approvedAt:null },
    { id:"apr-004", supplierId:"sup-002", supplierName:"Meridian Logistics", supplierInitial:"M", supplierColor:"#2B5BD7", invoiceNumber:"INV-4823", amount:5280, due:"Apr 22", dueIn:"3 days", urgent:false, category:"Freight", status:"approved", submittedBy:"Alex Rivera", submittedAt:"Apr 3, 10:30 AM",
      lineItems:[{desc:"Freight Manchester - London",qty:2,unit:1840.00},{desc:"Fuel surcharge",qty:2,unit:275.00},{desc:"Liftgate service",qty:1,unit:50.00}],
      subtotal:4280, tax:856,
      thread:[{time:"Apr 3 10:30 AM",kind:"submitted",who:"Alex Rivera",body:"Regular shipment invoice from Meridian."},{time:"Apr 5 2:15 PM",kind:"approved",who:"Jordan Lee",body:"Approved. Standard rate, all checks out."}],
      needsFollowUp:false, approvedBy:"Jordan Lee", approvedAt:"Apr 5" },
    { id:"apr-005", supplierId:"sup-009", supplierName:"Summit Ingredients", supplierInitial:"S", supplierColor:"#16794E", invoiceNumber:"INV-4825", amount:7890, due:"May 5", dueIn:"16 days", urgent:false, category:"Food Supply", status:"approved", submittedBy:"Casey Morgan", submittedAt:"Apr 6, 9:00 AM",
      lineItems:[{desc:"Organic flour (25kg bags)",qty:20,unit:245.00},{desc:"Olive oil (5L tins)",qty:12,unit:89.50},{desc:"Sea salt (bulk 10kg)",qty:8,unit:34.00}],
      subtotal:6446, tax:1289.20,
      thread:[{time:"Apr 6 9:00 AM",kind:"submitted",who:"Casey Morgan",body:"Weekly standing order from Summit."},{time:"Apr 7 11:45 AM",kind:"approved",who:"Jordan Lee",body:"Approved. Matches PO and delivery receipt."}],
      needsFollowUp:false, approvedBy:"Jordan Lee", approvedAt:"Apr 7" },
    { id:"apr-006", supplierId:"sup-001", supplierName:"Redwood Packaging Co.", supplierInitial:"R", supplierColor:"#B04A1D", invoiceNumber:"INV-4838", amount:4250, due:"May 15", dueIn:"26 days", urgent:false, category:"Packaging", status:"rejected", submittedBy:"Taylor Kim", submittedAt:"Apr 8, 1:30 PM",
      lineItems:[{desc:"Premium gift boxes (100 units)",qty:100,unit:34.00},{desc:"Ribbon spools (silk)",qty:50,unit:12.50},{desc:"Rush processing fee",qty:1,unit:175.00}],
      subtotal:4050, tax:200,
      thread:[{time:"Apr 8 1:30 PM",kind:"submitted",who:"Taylor Kim",body:"Premium packaging for VIP client gift boxes."},{time:"Apr 10 9:00 AM",kind:"rejected",who:"Jordan Lee",body:"Quantity seems high for a single client order. Can we reduce to 50 units and remove rush fee?"},{time:"Apr 10 11:15 AM",kind:"revised",who:"Taylor Kim",body:null,revision:"Reduced to 50 gift boxes, removed rush fee. New total: £2,325"}],
      needsFollowUp:true, approvedBy:null, approvedAt:null },
    { id:"apr-007", supplierId:"sup-003", supplierName:"Kettle & Hearth Supplies", supplierInitial:"K", supplierColor:"#6B4C9A", invoiceNumber:"INV-4836", amount:2180, due:"Apr 7", dueIn:"Paid", urgent:false, category:"Catering", status:"paid", submittedBy:"Alex Rivera", submittedAt:"Mar 10, 4:00 PM",
      lineItems:[{desc:"Tea selection box (12 varieties)",qty:10,unit:135.00},{desc:"Sugar sachets (box of 500)",qty:5,unit:28.00},{desc:"Milk portions (crate of 120)",qty:8,unit:18.75}],
      subtotal:1640, tax:328,
      thread:[{time:"Mar 10 4:00 PM",kind:"submitted",who:"Alex Rivera",body:"Monthly catering supplies."},{time:"Mar 12 10:00 AM",kind:"approved",who:"Jordan Lee",body:"Approved."},{time:"Apr 5 9:30 AM",kind:"paid",who:"System",body:"Payment processed via Bank Transfer."}],
      needsFollowUp:false, approvedBy:"Jordan Lee", approvedAt:"Mar 12" },
    { id:"apr-008", supplierId:"sup-010", supplierName:"Avalon Freight Solutions", supplierInitial:"A", supplierColor:"#B25A1C", invoiceNumber:"INV-4837", amount:4820, due:"Apr 11", dueIn:"Paid", urgent:false, category:"Logistics", status:"paid", submittedBy:"Casey Morgan", submittedAt:"Mar 14, 2:00 PM",
      lineItems:[{desc:"Air freight Cardiff - Edinburgh",qty:1,unit:3800.00},{desc:"Customs clearance",qty:1,unit:250.00},{desc:"Handling fees",qty:1,unit:166.67}],
      subtotal:4216.67, tax:843.33,
      thread:[{time:"Mar 14 2:00 PM",kind:"submitted",who:"Casey Morgan",body:"Time-sensitive shipment for client delivery."},{time:"Mar 14 4:30 PM",kind:"approved",who:"Jordan Lee",body:"Approved - expedite payment."},{time:"Apr 10 10:00 AM",kind:"paid",who:"System",body:"Payment processed via Bank Transfer."}],
      needsFollowUp:false, approvedBy:"Jordan Lee", approvedAt:"Mar 14" },
  ],

  history: [
    { id:"his-001", date:"Apr 10", day:"Today", supplierName:"Avalon Freight Solutions", method:"Bank Transfer", amount:4820, status:"paid", color:"#B25A1C", initial:"A" },
    { id:"his-002", date:"Apr 9", day:"Yesterday", supplierName:"Northgate Facilities", method:"Bank Transfer", amount:2450, status:"processing", color:"#3A4558", initial:"N" },
    { id:"his-003", date:"Apr 7", day:"Monday", supplierName:"Summit Ingredients", method:"Bank Transfer", amount:6540, status:"paid", color:"#16794E", initial:"S" },
    { id:"his-004", date:"Apr 5", day:"Saturday", supplierName:"Kettle & Hearth Supplies", method:"Bank Transfer", amount:2180, status:"paid", color:"#6B4C9A", initial:"K" },
    { id:"his-005", date:"Apr 5", day:"Saturday", supplierName:"Juniper Cleaning Services", method:"Faster Payment", amount:1420, status:"paid", color:"#2F6E3E", initial:"J" },
    { id:"his-006", date:"Apr 2", day:"Wednesday", supplierName:"Meridian Logistics", method:"Bank Transfer", amount:3870, status:"paid", color:"#2B5BD7", initial:"M" },
    { id:"his-007", date:"Mar 28", day:"Friday", supplierName:"Farrow Materials", method:"Bank Transfer", amount:9800, status:"paid", color:"#C23030", initial:"F" },
    { id:"his-008", date:"Mar 28", day:"Friday", supplierName:"Redwood Packaging Co.", method:"Bank Transfer", amount:5640, status:"paid", color:"#B04A1D", initial:"R" },
    { id:"his-009", date:"Mar 25", day:"Tuesday", supplierName:"Avalon Freight Solutions", method:"Bank Transfer", amount:3200, status:"failed", color:"#B25A1C", initial:"A" },
    { id:"his-010", date:"Mar 22", day:"Saturday", supplierName:"Kettle & Hearth Supplies", method:"Bank Transfer", amount:1890, status:"paid", color:"#6B4C9A", initial:"K" },
    { id:"his-011", date:"Mar 18", day:"Tuesday", supplierName:"Olive & Oak Linen Co.", method:"Bank Transfer", amount:3450, status:"paid", color:"#8B6914", initial:"O" },
  ],

  bankAccounts: [
    { name:"Barclays", label:"Operating", last4:"4829", balance:248920, color:"#00aeef" },
    { name:"HSBC", label:"Payroll", last4:"1187", balance:62140, color:"#e2000f" },
  ],

  team: [
    { name:"Jordan Morgan", email:"jordan@harbert.co.uk", role:"Admin", initials:"JM", color:"#2B5BD7" },
    { name:"Elena Chen", email:"elena@harbert.co.uk", role:"Approver", initials:"EC", color:"#16794E" },
    { name:"Marcus Webb", email:"marcus@harbert.co.uk", role:"Viewer", initials:"MW", color:"#6B4C9A" },
    { name:"Alex Rivera", email:"alex@harbert.co.uk", role:"Submitter", initials:"AR", color:"#B04A1D" },
    { name:"Casey Morgan", email:"casey@harbert.co.uk", role:"Submitter", initials:"CM", color:"#8B6914" },
    { name:"Taylor Kim", email:"taylor@harbert.co.uk", role:"Submitter", initials:"TK", color:"#C23030" },
  ],

  company: {
    name: "Harbert & Co",
    companyNumber: "12345678",
    vatNumber: "GB 123 4567 89",
    address: "14 Park Square, Sheffield S1 2FG",
    industry: "Manufacturing",
  },
};

function fmt(n) { return '£' + n.toLocaleString('en-GB', {minimumFractionDigits:2, maximumFractionDigits:2}); }
function fmtK(n) { return n >= 1000 ? '£' + (n/1000).toFixed(1) + 'k' : fmt(n); }
function getSupplier(id) { return DATA.suppliers.find(s => s.id === id); }
function getInvoicesForSupplier(id) { return DATA.invoices.filter(i => i.supplierId === id); }
